In [52]:
# torch로 Tensor 데이터 타입 다루기
import torch

tensor1 = torch.Tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

tensor2 = torch.Tensor([
    [13, 14, 15],
    [16, 17, 18],
    [19, 20, 21],
    [22, 23, 24]
])

test1 = tensor1.matmul(tensor2.view(3, 4))
test2 = tensor1.mul(tensor2)

print(test1)
print(test2)

print('ㅡ'*30)
tensor_cat = torch.cat([tensor1, tensor2], dim=1)
tensor_cat2 = torch.cat([tensor1, tensor2], dim=0)

print(tensor_cat)
print(tensor_cat2)


tensor([[110., 116., 122., 128.],
        [263., 278., 293., 308.],
        [416., 440., 464., 488.],
        [569., 602., 635., 668.]])
tensor([[ 13.,  28.,  45.],
        [ 64.,  85., 108.],
        [133., 160., 189.],
        [220., 253., 288.]])
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
tensor([[ 1.,  2.,  3., 13., 14., 15.],
        [ 4.,  5.,  6., 16., 17., 18.],
        [ 7.,  8.,  9., 19., 20., 21.],
        [10., 11., 12., 22., 23., 24.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.],
        [19., 20., 21.],
        [22., 23., 24.]])
